Toolbar and Headline Section
Zuwairanajma/Portfolio-Projects pull request #1
Opened 2023-06-02 04:10 UTC by Zuwairanajma

Here is the Toolbar and Headline Section for a mobile view portfolio project and I worked on the media query to ensure full width on all screens.

2023-06-02 05:41 UTC, NatiG25 requested changes
## :yellow_circle: CHANGES REQUIRED :yellow_circle: 

## Hi @Zuwairanajma :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Used the correct elements to make the project semantic.
:heavy_check_mark: Almost matched the Figma template.

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._
:x: I recommend you to include all main headers from the [README template](https://github.com/microverseinc/readme-template). Following Microverse's README template will help your project become more professional.
![image](https://github.com/Zuwairanajma/Portfolio-Projects/assets/86069740/ec85d4a1-f2bd-4fd2-a20c-0c0d7cf09376)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 05:41 UTC, NatiG25 commented on index.html
> +    <p class=""logo>My Logo</p>
- [ ] I suggest using an anchor tag (`a`) for your logo, that'll navigate to the home page. That way your project will become more semantic & improve UI.

2023-06-02 05:41 UTC, NatiG25 commented on index.html
> +                   <a href="https://twitter.com/@SadiqJuwairiyya"><img src ="PImages/Vector5.png" alt = "Medium Icon"></a></li>
- [ ] Great job! On using the `ul` for your social icons, but all icons, except for the first one, seem to miss an opening `li` tag. I recommend adding them to not face more errors.

2023-06-02 05:41 UTC, NatiG25 commented on index.html
> +            don’t hesitate to contact me.</p>
- [ ] I highly suggest that you follow the Figma template. Currently, there are some minor problems with your design:
<table>
<tr>
<th>Your design</th>
<th>Figma</th>
</tr>
  <tr>
    <td><img src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/86069740/22ae68ed-e0d3-4525-ab99-8c3730b1e39f"/></td>
    <td><img src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/86069740/3188014d-bcc1-4d61-89b7-f3670fa29ad0"/></td>
  </tr>
</table>

- Use the correct fonts for the title, sub-title & paragraph.
- Make sure to pack all of the elements to match the Figma design.

2023-06-02 09:54 UTC, franclobo requested changes
Hi @Zuwairanajma, 

# Required Changes ♻️

![soClose](https://github.com/Zuwairanajma/Portfolio-Projects/assets/58642949/7f92904a-356c-43c3-a388-f088139642af)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Best practices of HTML & CSS.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 09:54 UTC, franclobo commented on styles.css
> +  padding: 12px 151px 120px 24px;
- [ ] Kindly correct the padding and margin of the social icons to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://github.com/Zuwairanajma/Portfolio-Projects/assets/58642949/b1828c4b-ce5d-4044-aca9-11075d68b607) | ![image](https://github.com/Zuwairanajma/Portfolio-Projects/assets/58642949/3d8cd45b-b046-4515-941b-7303749c2bd1) |

2023-06-03 16:34 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED   
 ## Hi  @Zuwairanajma 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Well structured files :white_check_mark:
  * Good Job :+1: :smile: 
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [x] All is correct keep doing the great work :clap: 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 16:42 UTC, merged