Portfolio-Desktop version
Zuwairanajma/Portfolio-Projects pull request #5
Opened 2023-06-15 16:39 UTC by Zuwairanajma

Activities in this branch:
- I created a new branch.
- Added media queries for a min-width of 768px.
- Styled according to Figma template 2 desktop version.

2023-06-15 17:09 UTC, stanleySimeon requested changes
# Hi @Zuwairanajma, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media3.giphy.com/media/fQfSfrABMzaGMI6PR2/200w.webp?cid=5a38a5a2rdf86xjnv1rds21fm38plw0vaxitchg7ix9ouzp4&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
- Good PR desription
- Meaningful commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- adding your readme file

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 17:09 UTC, stanleySimeon commented on styles.css
> +  }
According to the Figma design kindly I suggest you stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)..

> ## Your Design
>
><img width="1440" alt="Screenshot 2023-06-15 at 12 48 36 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/cc9c770b-9f7b-45f7-aa70-13555c303ccb">
>
> ## The Figma Design
>
><img width="894" alt="Screenshot 2023-06-15 at 12 50 25 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/537fa688-35f5-4778-9eb2-e3a2e738d595">

2023-06-15 17:09 UTC, stanleySimeon commented on styles.css
> +  }
According to the Figma design kindly I suggest you stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)..

> ## Your Design
>
><img width="1439" alt="Screenshot 2023-06-15 at 12 52 14 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/36c09d99-e018-4cb8-a1cf-10854d354246">
>
> ## The Figma Design
>
><img width="842" alt="Screenshot 2023-06-15 at 12 53 54 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/f3ebc5aa-7ea8-49a4-8511-7c121f140943">

2023-06-15 17:09 UTC, stanleySimeon commented on styles.css
> +  }
According to the Figma design kindly I suggest you stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## Your Dsign
>
><img width="1437" alt="Screenshot 2023-06-15 at 12 56 27 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/d77229cb-944f-4c0d-a2db-3312838abf62">
><img width="1432" alt="Screenshot 2023-06-15 at 12 58 49 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/d20da31c-69ee-479e-a77c-c908b14db03b">
>
> ## The Figma Design
>
><img width="843" alt="Screenshot 2023-06-15 at 12 55 09 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/baf9ee65-fc0a-4c53-92fe-0506548282e1">
><img width="844" alt="Screenshot 2023-06-15 at 12 58 01 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/9a56e8bf-ca82-4a7d-be18-583680719219">

2023-06-15 17:09 UTC, stanleySimeon commented on styles.css
> +  }
According to the Figma design kindly I suggest you stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## Your Design
>
><img width="1440" alt="Screenshot 2023-06-15 at 1 00 42 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/b5ff9477-da7c-446a-94f5-24c190000860">
><img width="1440" alt="Screenshot 2023-06-15 at 1 01 46 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/b0359323-efee-49cd-ae3d-7df87b1d8b52">
>
> ## The Figma Design
>
><img width="1440" alt="Screenshot 2023-06-15 at 1 01 32 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/c80c2c49-287c-414b-8791-34124cda5afa">
><img width="1440" alt="Screenshot 2023-06-15 at 1 01 08 PM" src="https://github.com/Zuwairanajma/Portfolio-Projects/assets/91237525/8cc01e2f-410a-460b-8cd3-02637157b469">

2023-06-16 10:59 UTC, Strangeal approved these changes
Hi @Zuwairanajma, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 11:03 UTC, merged